FROM node:20-alpine AS builder
WORKDIR /app
COPY ./front-end/package*.json ./
RUN npm ci
COPY ./front-end ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /var/www
RUN rm /etc/nginx/conf.d/default.conf
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]