USE `SHUKKETSU_BUGYO`;

CREATE TABLE `TENANTS` (
    `TENANT_ID`      VARCHAR(30) PRIMARY KEY,
    `TENANT_NAME`    VARCHAR(255) NOT NULL,
    `TENANT_NAME_EN` VARCHAR(255) NOT NULL
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `TEACHERS` (
    `TENANT_ID`  VARCHAR(30) NOT NULL,
    `TEACHER_ID` VARCHAR(20) NOT NULL,
    `PASSWORD`   VARCHAR(255) NOT NULL,
    `MANAGER`    BOOLEAN     NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`TENANT_ID`, `TEACHER_ID`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `COURSES` (
    `TENANT_ID`      VARCHAR(30) NOT NULL,
    `COURSE_ID`      CHAR(36)    NOT NULL,
    `COURSE_NAME`    VARCHAR(255),
    `COURSE_NAME_EN` VARCHAR(255),
    PRIMARY KEY (`TENANT_ID`, `COURSE_ID`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `CLASSES` (
    `TENANT_ID`  VARCHAR(30) NOT NULL,
    `GRADE`      CHAR(1)     NOT NULL,
    `CLASS`      VARCHAR(15) NOT NULL,
    `TEACHER_ID` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`TENANT_ID`, `GRADE`, `CLASS`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `TEACHER_ID`) REFERENCES `TEACHERS`(`TENANT_ID`, `TEACHER_ID`) ON DELETE CASCADE
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `STUDENTS` (
    `TENANT_ID`  VARCHAR(30) NOT NULL,
    `STUDENT_ID` VARCHAR(20) NOT NULL,
    `GRADE`      CHAR(1),
    `CLASS`      VARCHAR(15),
    `NUMBER`     TINYINT UNSIGNED,
    `PASSWORD`   VARCHAR(255) NOT NULL,
    `COURSE_ID`  CHAR(36),
    PRIMARY KEY (`TENANT_ID`, `STUDENT_ID`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `GRADE`, `CLASS`) REFERENCES `CLASSES`(`TENANT_ID`, `GRADE`, `CLASS`) ON DELETE SET NULL,
    INDEX `idx_students_grade_class` (`GRADE`, `CLASS`)
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `LESSONS` (
    `TENANT_ID`      VARCHAR(30) NOT NULL,
    `LESSON_ID`      CHAR(36)    NOT NULL,
    `TEACHER_ID`     VARCHAR(20) NOT NULL,
    `LESSON_NAME`    VARCHAR(255),
    `LESSON_NAME_EN` VARCHAR(255),
    `GRADE`          CHAR(1)     NOT NULL,
    PRIMARY KEY (`TENANT_ID`, `LESSON_ID`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `TEACHER_ID`) REFERENCES `TEACHERS`(`TENANT_ID`, `TEACHER_ID`) ON DELETE CASCADE,
    INDEX `idx_lessons_teacher` (`TEACHER_ID`),
    INDEX `idx_lessons_grade` (`GRADE`)
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `ENROLLMENTS` (
    `ENROLLMENT_ID`   CHAR(36)    PRIMARY KEY,
    `TENANT_ID`       VARCHAR(30) NOT NULL,
    `STUDENT_ID`      VARCHAR(20) NOT NULL,
    `LESSON_ID`       CHAR(36)    NOT NULL,
    `STATUS`          TINYINT     NOT NULL DEFAULT 1,
    UNIQUE KEY `unique_student_lesson` (`TENANT_ID`, `STUDENT_ID`, `LESSON_ID`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `STUDENT_ID`) REFERENCES `STUDENTS`(`TENANT_ID`, `STUDENT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `LESSON_ID`) REFERENCES `LESSONS`(`TENANT_ID`, `LESSON_ID`) ON DELETE CASCADE,
    INDEX `idx_enrollments_student` (`STUDENT_ID`),
    INDEX `idx_enrollments_lesson` (`LESSON_ID`)
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `TIME_SLOTS` (
    `TENANT_ID`  VARCHAR(30) NOT NULL,
    `PERIOD`     VARCHAR(20) NOT NULL,
    `START_TIME` TIME        NOT NULL,
    `END_TIME`   TIME        NOT NULL,
    PRIMARY KEY (`TENANT_ID`, `PERIOD`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `TIME_TABLE` (
    `TENANT_ID`   VARCHAR(30) NOT NULL,
    `LESSON_ID`   CHAR(36)    NOT NULL,
    `PERIOD`      VARCHAR(20) NOT NULL,
    `DAY_OF_WEEK` TINYINT UNSIGNED NOT NULL,
    `GRADE`       CHAR(1)     NOT NULL,
    `CLASS`       VARCHAR(15) NOT NULL,
    PRIMARY KEY (`TENANT_ID`, `LESSON_ID`, `PERIOD`, `DAY_OF_WEEK`, `GRADE`, `CLASS`),
    FOREIGN KEY (`TENANT_ID`, `LESSON_ID`) REFERENCES `LESSONS`(`TENANT_ID`, `LESSON_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `GRADE`, `CLASS`) REFERENCES `CLASSES`(`TENANT_ID`, `GRADE`, `CLASS`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `PERIOD`) REFERENCES `TIME_SLOTS`(`TENANT_ID`, `PERIOD`) ON DELETE CASCADE,
    INDEX `idx_timetable_class` (`GRADE`, `CLASS`),
    INDEX `idx_timetable_period_day` (`PERIOD`, `DAY_OF_WEEK`)
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `ATTENDANCE` (
    `TENANT_ID`     VARCHAR(30) NOT NULL,
    `ENROLLMENT_ID` CHAR(36)    NOT NULL,
    `STUDENT_ID`    VARCHAR(20) NOT NULL,
    `DATE`          DATE        NOT NULL,
    `PERIOD`        VARCHAR(20) NOT NULL,
    `STATUS`        TINYINT     NOT NULL DEFAULT 0,
    `NOTES`         TEXT,
    PRIMARY KEY (`TENANT_ID`, `ENROLLMENT_ID`, `STUDENT_ID`, `DATE`, `PERIOD`),
    FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANTS`(`TENANT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`ENROLLMENT_ID`) REFERENCES `ENROLLMENTS`(`ENROLLMENT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `STUDENT_ID`) REFERENCES `STUDENTS`(`TENANT_ID`, `STUDENT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`TENANT_ID`, `PERIOD`) REFERENCES `TIME_SLOTS`(`TENANT_ID`, `PERIOD`) ON DELETE CASCADE,
    INDEX `idx_attendance_date` (`DATE`),
    INDEX `idx_attendance_student_date` (`STUDENT_ID`, `DATE`)
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;